project_id = "nnfaawrtzvzyqvpgvcxu"

[functions.llm-caller]
verify_jwt = true

[functions.mentor-copilot-chat]
verify_jwt = true

[functions.mentor-learning-path]
verify_jwt = true

[functions.mock-interview]
verify_jwt = true

[functions.admin-azure-storage]
verify_jwt = true

[functions.send-auth-email]
verify_jwt = false

